# -- coding: utf-8 --

# Form implementation generated from reading ui file 'task1_test2.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import matplotlib
import matplotlib.pyplot as plt
from PyQt5.QtWidgets import QFileDialog, QGridLayout, QSlider, QLabel, QVBoxLayout, QHBoxLayout
from PyQt5.QtCore import Qt, QPoint
from PyQt5.QtGui import QPainter, QColor
from PyQt5.QtWidgets import QLabel, QGraphicsDropShadowEffect
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg, NavigationToolbar2QT as Navi
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
from matplotlib.figure import Figure
#import pyedflib 
from PyQt5.QtCore import QTimer
import pyqtgraph as pg
import numpy as np


       
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1170, 1022)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: rgb(34, 40, 62);")
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonFollowStyle)
        MainWindow.setAnimated(True)
        MainWindow.setDocumentMode(False)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        MainWindow.setDockNestingEnabled(True)
        MainWindow.setUnifiedTitleAndToolBarOnMac(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(5, 5, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.graph1Widget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayout_2.addWidget(self.graph1Widget)
        self.graph1Widget.num = 0
        self.graph1Widget.graph = pg.PlotWidget(self.graph1Widget)
        self.graph1Widget.graph.setBackground('#2D324D')
        self.graph1Widget.graph.setMouseEnabled(x=True, y=True)
        self.graph1Widget.grid_graph_3 = QGridLayout()
        self.graph1Widget.timer = QTimer()
        self.graph1Widget.setLayout(self.graph1Widget.grid_graph_3)
        self.graph1Widget.grid_graph_3.addWidget(self.graph1Widget.graph, 0, 0, 1, 1)
        self.graph1Widget.timer.start(100)
        self.graph1Widget.show()
        
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graph1Widget.sizePolicy().hasHeightForWidth())
        self.graph1Widget.setSizePolicy(sizePolicy)
        self.graph1Widget.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.graph1Widget.setMouseTracking(True)
        self.graph1Widget.setTabletTracking(True)
        self.graph1Widget.setAcceptDrops(True)
        self.graph1Widget.setAutoFillBackground(False)
        self.graph1Widget.setStyleSheet("background-color: rgb(45, 50, 77);\n"
"border-radius: 25px;\n"
"buttoon-shadow: 2px 2px 5px rgb(0, 0, 0);\n"
"widget-shadow: 2px 2px 5px rgb(0, 0, 0);")
        self.graph1Widget.setObjectName("graph1Widget")
        
       
        self.line = QtWidgets.QFrame(self.graph1Widget)
        self.line.setGeometry(QtCore.QRect(640, 20, 61, 20))
        self.line.setStyleSheet("\n"
"color: rgb(0, 0, 0);")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        



        





        
        self.frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setMinimumSize(QtCore.QSize(350, 0))
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setStyleSheet("background-color: rgb(45, 50, 77);\n"
"border-radius: 25px;\n"
"buttoon-shadow: 2px 2px 5px rgb(0, 0, 0);\n"
"widget-shadow: 2px 2px 5px rgb(0, 0, 0);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.signal_color_button_graph_1 = QtWidgets.QPushButton(self.frame)
        self.signal_color_button_graph_1.setCursor(QtGui.QCursor(QtCore.Qt.SplitVCursor))
        self.signal_color_button_graph_1.setMouseTracking(True)
        self.signal_color_button_graph_1.setStyleSheet("font: italic 10pt \"Georgia\";\n"
"font: 12pt \"Georgia\";\n"
"\n"
"color: rgb(34, 40, 62);\n"
"background-color: rgb(120, 207, 233);\n"
"buttoon-shadow: 2px 2px 5px rgb(0, 0, 0);\n"
"border-radius: 10px;")
        self.signal_color_button_graph_1.setObjectName("signal_color_button_graph_1")
        self.gridLayout.addWidget(self.signal_color_button_graph_1, 2, 1, 1, 1)
        self.signal_name_lineEdit_graph_1 = QtWidgets.QLineEdit(self.frame)
        self.signal_name_lineEdit_graph_1.setStyleSheet("border-radius: 10px;\n"
"border-shadow: 2px 2px 5px rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.signal_name_lineEdit_graph_1.setObjectName("signal_name_lineEdit_graph_1")
        self.gridLayout.addWidget(self.signal_name_lineEdit_graph_1, 1, 1, 1, 1)
        self.visible_checkBox_graph_1 = QtWidgets.QCheckBox(self.frame)
        self.visible_checkBox_graph_1.setChecked(True)
        self.visible_checkBox_graph_1.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: italic 10pt \"Georgia\";\n"
"\n"
"")
        self.visible_checkBox_graph_1.setObjectName("visible_checkBox_graph_1")
        self.gridLayout.addWidget(self.visible_checkBox_graph_1, 2, 0, 1, 1)



        self.signal_name_label_graph_1 = QtWidgets.QLabel(self.frame)
        self.signal_name_label_graph_1.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: italic 10pt \"Georgia\";\n"
"")
        self.signal_name_label_graph_1.setObjectName("signal_name_label_graph_1")
        self.gridLayout.addWidget(self.signal_name_label_graph_1, 1, 0, 1, 1)

       
        self.speed_label_graph_1 = QtWidgets.QLabel(self.frame)
        self.speed_label_graph_1.setObjectName("speed_label_graph_1")
        self.speed_label_graph_1.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: italic 10pt \"Georgia\";\n"
"")
        self.speed_slider_graph_1 = QtWidgets.QSlider(QtCore.Qt.Horizontal, self.frame)
        self.speed_slider_graph_1.setObjectName("speed_slider_graph_1 ")
        self.speed_slider_graph_1.setStyleSheet("""
    QSlider::groove:horizontal {
        height: 8px;
        background: #C1EFFE;
        border-radius: 4px;
    }
    QSlider::handle:horizontal {
        background: #78CEE8;
        border: 2px solid #C1EFFE;
        width: 20px;
        height: 20px;
        margin: -6px 0;
        border-radius: 10px;
    }
    QSlider::sub-page:horizontal {
        background: #78CEE8;
        border-radius: 4px;
    }
    QSlider::add-page:horizontal {
        background: #C1EFFE;
        border-radius: 4px;
    }
""")
        self.speed_slider_graph_1.setMinimum(10)  # Minimum speed interval (in ms)
        self.speed_slider_graph_1.setMaximum(60)  # Maximum speed interval (in ms)
        self.speed_slider_graph_1.setValue(40)  # Default speed interval (in ms)
        
        self.gridLayout.addWidget(self.speed_slider_graph_1, 3, 1, 1, 1)
        self.gridLayout.addWidget(self.speed_label_graph_1, 3, 0, 1, 1)


        self.select_signal_name_label_graph_1 = QtWidgets.QLabel(self.frame)
        self.select_signal_name_label_graph_1.setObjectName("select_signal_name_graph_1")
        self.select_signal_name_label_graph_1.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: italic 10pt \"Georgia\";\n"
"")
        self.gridLayout.addWidget(self.select_signal_name_label_graph_1, 0, 0, 1, 1)


        self.signals_name_combo_box_graph_1 = QtWidgets.QComboBox(self.frame)
        self.signals_name_combo_box_graph_1.setObjectName("signals_name_combo_box_graph_1")
        self.signals_name_combo_box_graph_1.setStyleSheet("""
            QComboBox {
                background-color: #3c4a68;  /* Background color */
                color: white;  /* Text color */
                border: 1px solid #3c4a68;
                border-radius: 10px;  /* Rounded corners */
                padding: 5px;
                font-size: 14px;
                box-shadow: 2px 2px 5px rgba(0, 0, 0, 0.3);  /* Shadow */
            }
            QComboBox::drop-down {
                border: none;
                border-radius: 10px;  /* Rounded corners for the arrow box */
                background-color: #3c4a68;
                width: 30px;
            }
            QComboBox::down-arrow {
                # image: url(down_arrow.png);  /* You can replace this with a custom arrow icon */
                width: 15px;
                height: 15px;
            }
            QComboBox::down-arrow {
                border: none;
                color: white;  /* Arrow color */
            }
            QComboBox QAbstractItemView {
                border: 1px solid #3c4a68;
                selection-background-color: #5a6478;  /* Selected item background color */
                background-color: #3c4a68;  /* Dropdown background color */
                color: white;
                border-radius: 10px;
            }
        """)


        self.gridLayout.addWidget(self.signals_name_combo_box_graph_1, 0, 1, 1, 1)

        self.horizontalLayout_2.addWidget(self.frame)
        self.gridLayout_4.addLayout(self.horizontalLayout_2, 3, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(15, -1, 365, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        
        self.link_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.link_button.sizePolicy().hasHeightForWidth())
        self.link_button.setSizePolicy(sizePolicy)
        self.link_button.setMinimumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.link_button.setFont(font)
        self.link_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.link_button.setStyleSheet("font: italic 10pt \"Georgia\";\n"
"font: 12pt \"Georgia\";\n"
"\n"
"color: rgb(34, 40, 62);\n"
"background-color: rgb(120, 207, 233);\n"
"buttoon-shadow: 2px 2px 5px rgb(0, 0, 0);\n"
"border-radius: 10px;")
        self.link_button.setObjectName("link_button")
        self.horizontalLayout_3.addWidget(self.link_button)
        
        self.link_play_button = QtWidgets.QPushButton(self.centralwidget)
        self.link_play_button.setCursor(QtGui.QCursor(QtCore.Qt.SplitVCursor))
        self.link_play_button.setMouseTracking(True)
        self.link_play_button.setStyleSheet("font: italic 10pt \"Georgia\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(120, 207, 233);\n"
"buttoon-shadow: 2px 2px 5px rgb(0, 0, 0);\n"
"border-radius: 15px;")
        self.link_play_button.setText("")
        self.icon = QtGui.QIcon()
        self.icon.addPixmap(QtGui.QPixmap(".\images\icons8-pause-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.link_play_button.setIcon(self.icon)
        self.link_play_button.setObjectName("link_play_button")
        self.horizontalLayout_3.addWidget(self.link_play_button)
        self.link_play_button.setCursor(QtCore.Qt.PointingHandCursor)
        self.link_play_button.hide()
        
        self.link_rewind_button = QtWidgets.QPushButton(self.centralwidget)
        self.link_rewind_button.setCursor(QtGui.QCursor(QtCore.Qt.SplitVCursor))
        self.link_rewind_button.setMouseTracking(True)
        self.link_rewind_button.setStyleSheet("font: italic 10pt \"Georgia\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(120, 207, 233);\n"
"buttoon-shadow: 2px 2px 5px rgb(0, 0, 0);\n"
"border-radius: 15px;")
        self.link_rewind_button.setText("")
        self.icon_rewind = QtGui.QIcon()
        self.icon_rewind.addPixmap(QtGui.QPixmap(".\images\icons8-rewind-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.link_rewind_button.setIcon(self.icon_rewind)
        self.link_rewind_button.setObjectName("link_rewind_button")
        self.horizontalLayout_3.addWidget(self.link_rewind_button)
        self.link_rewind_button.setCursor(QtCore.Qt.PointingHandCursor)
        self.link_rewind_button.hide()
        
        
        
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        select_2 = QtGui.QIcon()
        select_2.addPixmap(QtGui.QPixmap("./images/icons8-screenshot-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.select_button_graph2 = QtWidgets.QPushButton(self.centralwidget)
        self.select_button_graph2.setIcon(select_2)
        self.select_button_graph2.setMinimumSize(QtCore.QSize(30, 30))
        self.select_button_graph2.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.select_button_graph2.setToolTipDuration(-1)
        self.select_button_graph2.setStyleSheet("font: italic 10pt \"Georgia\";\n"
"font: 12pt \"Georgia\";\n"
"\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(120, 207, 233);\n"
"buttoon-shadow: 2px 2px 5px rgb(0, 0, 0);\n"
"border-radius: 15px;")
        self.select_button_graph2.setText("")
        snapshot_2 = QtGui.QIcon()
        snapshot_2.addPixmap(QtGui.QPixmap("./images/icons8-camera-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        
        self.select_button_graph2.setObjectName("select_button_graph2")
        self.horizontalLayout_3.addWidget(self.select_button_graph2)
        self.snapshot_button_graph2 = QtWidgets.QPushButton(self.centralwidget)
        self.snapshot_button_graph2.setIcon(snapshot_2)
        self.snapshot_button_graph2.setMinimumSize(QtCore.QSize(30, 30))
        self.snapshot_button_graph2.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.snapshot_button_graph2.setStyleSheet("font: italic 10pt \"Georgia\";\n"
"font: 12pt \"Georgia\";\n"
"\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(120, 207, 233);\n"
"buttoon-shadow: 2px 2px 5px rgb(0, 0, 0);\n"
"border-radius: 15px;")
        self.snapshot_button_graph2.setText("")
        self.snapshot_button_graph2.setObjectName("snapshot_button_graph2")
        self.horizontalLayout_3.addWidget(self.snapshot_button_graph2)
        
        self.play_button_graph_2 = QtWidgets.QPushButton(self.centralwidget)
        self.play_button_graph_2.setCursor(QtGui.QCursor(QtCore.Qt.SplitVCursor))
        self.play_button_graph_2.setMouseTracking(True)
        self.play_button_graph_2.setStyleSheet("font: italic 10pt \"Georgia\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(120, 207, 233);\n"
"buttoon-shadow: 2px 2px 5px rgb(0, 0, 0);\n"
"border-radius: 15px;")
        self.play_button_graph_2.setText("")
        self.icon = QtGui.QIcon()
        self.icon.addPixmap(QtGui.QPixmap(".\images\icons8-pause-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.play_button_graph_2.setIcon(self.icon)
        self.play_button_graph_2.setObjectName("play_button_graph_2")
        self.horizontalLayout_3.addWidget(self.play_button_graph_2)
        self.select_button_graph_2 = QtWidgets.QPushButton(self.centralwidget)
        self.select_button_graph_2.setCursor(QtGui.QCursor(QtCore.Qt.SplitVCursor))
        self.select_button_graph_2.setMouseTracking(True)
        self.select_button_graph_2.setStyleSheet("font: italic 10pt \"Georgia\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(120, 207, 233);\n"
"buttoon-shadow: 2px 2px 5px rgb(0, 0, 0);\n"
"border-radius: 15px;")
        self.select_button_graph_2.setText("")
        self.icon1 = QtGui.QIcon()
        self.icon1.addPixmap(QtGui.QPixmap(".\images\icons8-audio-wave-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pause = QtGui.QIcon()
        self.pause.addPixmap(QtGui.QPixmap(".\images\icons8-play-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        
        self.select_button_graph_2.setIcon(self.icon1)
        self.select_button_graph_2.setObjectName("select_button_graph_2")
        self.horizontalLayout_3.addWidget(self.select_button_graph_2)
        self.reset_button_graph_2 = QtWidgets.QPushButton(self.centralwidget)
        self.reset_button_graph_2.setCursor(QtGui.QCursor(QtCore.Qt.SplitVCursor))
        self.reset_button_graph_2.setMouseTracking(True)
        self.reset_button_graph_2.setStyleSheet("font: italic 10pt \"Georgia\";\n"
"color: rgb(34, 40, 62);\n"
"background-color:rgb(120, 207, 233);\n"
"buttoon-shadow: 2px 2px 5px rgb(0, 0, 0);\n"
"border-radius: 15px;")
        self.reset_button_graph_2.setText("ON")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("./images/icons8-play-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.reset_button_graph_2.setIcon(icon2)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("./images/icons8-rewind-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.reset_button_graph_2.setIcon(icon6)
        self.reset_button_graph_2.setObjectName("reset_button_graph_2")
        self.horizontalLayout_3.addWidget(self.reset_button_graph_2)
        self.move_to_graph_1_button = QtWidgets.QPushButton(self.centralwidget)
        self.move_to_graph_1_button.setCursor(QtGui.QCursor(QtCore.Qt.SplitVCursor))
        self.move_to_graph_1_button.setMouseTracking(True)
        self.move_to_graph_1_button.setStyleSheet("font: italic 10pt \"Georgia\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(120, 207, 233);\n"
"buttoon-shadow: 2px 2px 5px rgb(0, 0, 0);\n"
"border-radius: 15px;")
        self.move_to_graph_1_button.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("./images/icons8-up-arrow-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.move_to_graph_1_button.setIcon(icon3)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("./images/icons8-down-arrow-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        # self.move_to_graph_2_button.setIcon(icon5)
        self.move_to_graph_1_button.setObjectName("move_to_graph_1_button")
        self.horizontalLayout_3.addWidget(self.move_to_graph_1_button)
        self.connect_online_button_graph_2 = QtWidgets.QPushButton(self.centralwidget)
        self.connect_online_button_graph_2.setCursor(QtGui.QCursor(QtCore.Qt.SplitVCursor))
        self.connect_online_button_graph_2.setMouseTracking(True)
        self.connect_online_button_graph_2.setStyleSheet("font: italic 10pt \"Georgia\";\n"
"color: rgb(34, 40, 62);\n"
"background-color: rgb(120, 207, 233);\n"
"buttoon-shadow: 2px 2px 5px rgb(0, 0, 0);\n"
"border-radius: 10px;")
        self.connect_online_button_graph_2.setText("Connect Online")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("./images/icons8-zoom-out-64.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.connect_online_button_graph_2.setObjectName("connect_online_button_graph_2")
       
        
        self.horizontalLayout_3.addWidget(self.connect_online_button_graph_2)
        self.open_button_graph_2 = QtWidgets.QPushButton(self.centralwidget)
        self.open_button_graph_2.setCursor(QtGui.QCursor(QtCore.Qt.SplitVCursor))
        self.open_button_graph_2.setMouseTracking(True)
        self.open_button_graph_2.setStyleSheet("font: italic 10pt \"Georgia\";\n"
"font: 12pt \"Georgia\";\n"
"\n"
"color: rgb(34, 40, 62);\n"
"background-color: rgb(120, 207, 233);\n"
"buttoon-shadow: 2px 2px 5px rgb(0, 0, 0);\n"
"border-radius: 10px;")
        self.open_button_graph_2.setObjectName("open_button_graph_2")
        self.horizontalLayout_3.addWidget(self.open_button_graph_2)
        self.gridLayout_4.addLayout(self.horizontalLayout_3, 4, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem2 = QtWidgets.QSpacerItem(5, 5, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.graph1Widget_3 = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graph1Widget_3.sizePolicy().hasHeightForWidth())
        self.graph1Widget_3.setSizePolicy(sizePolicy)
        self.graph1Widget_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.graph1Widget_3.setMouseTracking(True)
        self.graph1Widget_3.setTabletTracking(True)
        self.graph1Widget_3.setAcceptDrops(True)
        self.graph1Widget_3.setAutoFillBackground(False)
        self.graph1Widget_3.setStyleSheet("background-color: rgb(45, 50, 77);\n"
"border-radius: 25px;\n"
"buttoon-shadow: 2px 2px 5px rgb(0, 0, 0);\n"
"widget-shadow: 2px 2px 5px rgb(0, 0, 0);")
        self.graph1Widget_3.setObjectName("graph1Widget_3")
        self.horizontalLayout_6.addWidget(self.graph1Widget_3)



        self.graph1Widget_3.num = 0
        self.graph1Widget_3.graph = pg.PlotWidget(self.graph1Widget_3)
        self.graph1Widget_3.graph.setBackground('#2D324D') 
        self.graph1Widget_3.graph.setMouseEnabled(x=True, y=True)
        self.graph1Widget_3.grid_graph_3 = QGridLayout()
        self.graph1Widget_3.timer = QTimer()
        self.graph1Widget_3.setLayout(self.graph1Widget_3.grid_graph_3)
        self.graph1Widget_3.grid_graph_3.addWidget(self.graph1Widget_3.graph, 0, 0, 1, 1)
        #self.graph1Widget_3.timer.timeout.connect(self.update)
        self.graph1Widget_3.timer.start(1000)
        self.graph1Widget_3.show()






        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setMinimumSize(QtCore.QSize(350, 0))
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setStyleSheet("background-color: rgb(45, 50, 77);\n"
"border-radius: 25px;\n"
"buttoon-shadow: 2px 2px 5px rgb(0, 0, 0);\n"
"widget-shadow: 2px 2px 5px rgb(0, 0, 0);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.signal_name_label_graph_3 = QtWidgets.QLabel(self.frame_3)
        self.signal_name_label_graph_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: italic 10pt \"Georgia\";\n"
"")
        self.signal_name_label_graph_3.setObjectName("signal_name_label_graph_3")
        self.slider_glue = QtWidgets.QSlider(self.frame_3)
        self.slider_glue.setOrientation(QtCore.Qt.Horizontal)
        self.slider_glue.setObjectName("slider_glue")
        self.gridLayout_3.addWidget(self.slider_glue, 3, 0, 1, 2)
        
        self.pushButton = QtWidgets.QPushButton(self.frame_3)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setMouseTracking(True)
        self.pushButton.setStyleSheet("font: italic 10pt \"Georgia\";\n"
"font: 12pt \"Georgia\";\n"
"\n"
"color: rgb(34, 40, 62);\n"
"background-color: rgb(120, 207, 233);\n"
"buttoon-shadow: 2px 2px 5px rgb(0, 0, 0);\n"
"border-radius: 10px;")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_3.addWidget(self.pushButton, 4, 0, 1, 1)
       
        self.gridLayout_3.addWidget(self.signal_name_label_graph_3, 0, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.frame_3)
        self.comboBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.comboBox.setMouseTracking(True)
        self.comboBox.setStyleSheet("""
            QComboBox {
                background-color: #3c4a68;  /* Background color */
                color: white;  /* Text color */
                border: 1px solid #3c4a68;
                border-radius: 10px;  /* Rounded corners */
                padding: 5px;
                font-size: 14px;
                box-shadow: 2px 2px 5px rgba(0, 0, 0, 0.3);  /* Shadow */
            }
            QComboBox::drop-down {
                border: none;
                border-radius: 10px;  /* Rounded corners for the arrow box */
                background-color: #3c4a68;
                width: 30px;
            }
            QComboBox::down-arrow {
                # image: url(down_arrow.png);  /* You can replace this with a custom arrow icon */
                width: 15px;
                height: 15px;
            }
            QComboBox::down-arrow {
                border: none;
                color: white;  /* Arrow color */
            }
            QComboBox QAbstractItemView {
                border: 1px solid #3c4a68;
                selection-background-color: #5a6478;  /* Selected item background color */
                background-color: #3c4a68;  /* Dropdown background color */
                color: white;
                border-radius: 10px;
            }
        """)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout_3.addWidget(self.comboBox, 0, 1, 1, 1)
        self.comboBox.addItems(["linear", "cubic"])
        
#         self.visible_checkBox_graph_3 = QtWidgets.QCheckBox(self.frame_3)
#         self.visible_checkBox_graph_3.setStyleSheet("color: rgb(255, 255, 255);\n"
# "font: italic 10pt \"Georgia\";\n"
# "\n"
# "")
#         self.visible_checkBox_graph_3.setObjectName("visible_checkBox_graph_3")
#         self.gridLayout_3.addWidget(self.visible_checkBox_graph_3, 1, 0, 1, 1)
#         self.signal_color_button_graph_3 = QtWidgets.QPushButton(self.frame_3)
#         self.signal_color_button_graph_3.setCursor(QtGui.QCursor(QtCore.Qt.SplitVCursor))
#         self.signal_color_button_graph_3.setMouseTracking(True)
#         self.signal_color_button_graph_3.setStyleSheet("font: italic 10pt \"Georgia\";\n"
# "font: 12pt \"Georgia\";\n"
# "\n"
# "color: rgb(255, 255, 255);\n"
# "background-color: rgb(120, 207, 233);\n"
# "buttoon-shadow: 2px 2px 5px rgb(0, 0, 0);\n"
# "border-radius: 10px;")
#         self.signal_color_button_graph_3.setObjectName("signal_color_button_graph_3")
#         self.gridLayout_3.addWidget(self.signal_color_button_graph_3, 1, 1, 1, 1)
        self.horizontalLayout_6.addWidget(self.frame_3)
        self.gridLayout_4.addLayout(self.horizontalLayout_6, 7, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(15, -1, 365, -1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.graph_Label_3 = QtWidgets.QLabel(self.centralwidget)
        self.graph_Label_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: italic 11pt \"Georgia\";\n"
"")
        self.graph_Label_3.setTextFormat(QtCore.Qt.PlainText)
        self.graph_Label_3.setObjectName("graph_Label_3")
        self.horizontalLayout_5.addWidget(self.graph_Label_3)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.snapshot3 = QtGui.QIcon()
        self.snapshot3.addPixmap(QtGui.QPixmap(".\images\icons8-camera-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        
        self.snapshot_button_graph_3 = QtWidgets.QPushButton(self.centralwidget)
        self.snapshot_button_graph_3.setCursor(QtGui.QCursor(QtCore.Qt.SplitVCursor))
        self.snapshot_button_graph_3.setMouseTracking(True)
        self.snapshot_button_graph_3.setStyleSheet("font: italic 10pt \"Georgia\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(120, 207, 233);\n"
"buttoon-shadow: 2px 2px 5px rgb(0, 0, 0);\n"
"border-radius: 15px;")
        self.snapshot_button_graph_3.setText("")
        self.snapshot_button_graph_3.setIcon(self.snapshot3)
        self.snapshot_button_graph_3.setObjectName("snapshot_button_graph_3")
        self.horizontalLayout_5.addWidget(self.snapshot_button_graph_3)
        
        self.gridLayout_4.addLayout(self.horizontalLayout_5, 6, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem4 = QtWidgets.QSpacerItem(5, 5, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.graph2Widget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graph2Widget.sizePolicy().hasHeightForWidth())
        self.graph2Widget.setSizePolicy(sizePolicy)
        self.graph2Widget.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.graph2Widget.setMouseTracking(True)
        self.graph2Widget.setTabletTracking(True)
        self.graph2Widget.setAcceptDrops(True)
        self.graph2Widget.setAutoFillBackground(False)
        self.graph2Widget.setStyleSheet("background-color: rgb(45, 50, 77);\n"
"border-radius: 25px;\n"
"buttoon-shadow: 2px 2px 5px rgb(0, 0, 0);\n"
"widget-shadow: 2px 2px 5px rgb(0, 0, 0);")
        self.graph2Widget.setObjectName("graph2Widget")
        self.horizontalLayout_4.addWidget(self.graph2Widget)




        self.graph2Widget.num = 0
        self.graph2Widget.graph_2 = pg.PlotWidget(self.graph2Widget)
        self.graph2Widget.graph_2.setBackground('#2D324D') 
        self.graph2Widget.grid_graph_2 = QGridLayout()
        self.graph2Widget.timer = QTimer()
        self.graph2Widget.setLayout(self.graph2Widget.grid_graph_2)
        self.graph2Widget.grid_graph_2.addWidget(self.graph2Widget.graph_2, 0, 0, 1, 1)
        #self.graph2Widget.timer.timeout.connect(self.update)
        self.graph2Widget.timer.start(1000)
        self.graph2Widget.show()






        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setMinimumSize(QtCore.QSize(350, 0))
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setStyleSheet("background-color: rgb(45, 50, 77);\n"
"border-radius: 25px;\n"
"buttoon-shadow: 2px 2px 5px rgb(0, 0, 0);\n"
"widget-shadow: 2px 2px 5px rgb(0, 0, 0);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.signal_name_label_graph_2 = QtWidgets.QLabel(self.frame_2)
        self.signal_name_label_graph_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: italic 10pt \"Georgia\";\n"
"")
        self.signal_name_label_graph_2.setObjectName("signal_name_label_graph_2")
        self.gridLayout_2.addWidget(self.signal_name_label_graph_2, 1, 0, 1, 1)
        self.signal_name_lineEdit_graph_2 = QtWidgets.QLineEdit(self.frame_2)
        self.signal_name_lineEdit_graph_2.setStyleSheet("border-radius: 10px;\n"
"border-shadow: 2px 2px 5px rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.signal_name_lineEdit_graph_2.setObjectName("signal_name_lineEdit_graph_2")
        self.gridLayout_2.addWidget(self.signal_name_lineEdit_graph_2, 1, 1, 1, 1)
        self.visible_checkBox_graph_2 = QtWidgets.QCheckBox(self.frame_2)
        self.visible_checkBox_graph_2.setChecked(True)
        self.visible_checkBox_graph_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: italic 10pt \"Georgia\";\n"
"\n"
"")
        self.visible_checkBox_graph_2.setObjectName("visible_checkBox_graph_2")
        self.gridLayout_2.addWidget(self.visible_checkBox_graph_2, 2, 0, 1, 1)
        self.signal_color_button_graph_2 = QtWidgets.QPushButton(self.frame_2)
        self.signal_color_button_graph_2.setCursor(QtGui.QCursor(QtCore.Qt.SplitVCursor))
        self.signal_color_button_graph_2.setMouseTracking(True)
        self.signal_color_button_graph_2.setStyleSheet("font: italic 10pt \"Georgia\";\n"
"font: 12pt \"Georgia\";\n"
"\n"
"color: rgb(34, 40, 62);\n"
"background-color: rgb(120, 207, 233);\n"
"buttoon-shadow: 2px 2px 5px rgb(0, 0, 0);\n"
"border-radius: 10px;")
        self.signal_color_button_graph_2.setObjectName("signal_color_button_graph_2")
        self.gridLayout_2.addWidget(self.signal_color_button_graph_2, 2, 1, 1, 1)

 
        self.speed_label_graph_2 = QtWidgets.QLabel(self.frame_2)
        self.speed_label_graph_2.setObjectName("speed_label_graph_2")
        self.speed_label_graph_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: italic 10pt \"Georgia\";\n"
"")
        self.speed_slider_graph_2 = QtWidgets.QSlider(QtCore.Qt.Horizontal, self.frame_2)
        self.speed_slider_graph_2.setObjectName("speed_slider_graph_2 ")
        self.speed_slider_graph_2.setStyleSheet("""
    QSlider::groove:horizontal {
        height: 8px;
        background: #C1EFFE;
        border-radius: 4px;
    }
    QSlider::handle:horizontal {
        background: #78CEE8;
        border: 2px solid #C1EFFE;
        width: 20px;
        height: 20px;
        margin: -6px 0;
        border-radius: 10px;
    }
    QSlider::sub-page:horizontal {
        background: #78CEE8;
        border-radius: 4px;
    }
    QSlider::add-page:horizontal {
        background: #C1EFFE;
        border-radius: 4px;
    }
""")
        self.speed_slider_graph_2.setMinimum(10)  # Minimum speed interval (in ms)
        self.speed_slider_graph_2.setMaximum(60)  # Maximum speed interval (in ms)
        self.speed_slider_graph_2.setValue(40)  # Default speed interval (in ms)
        
        self.gridLayout_2.addWidget(self.speed_slider_graph_2, 3, 1, 1, 1)
        self.gridLayout_2.addWidget(self.speed_label_graph_2, 3, 0, 1, 1)



        self.select_signal_name_label_graph_2 = QtWidgets.QLabel(self.frame)
        self.select_signal_name_label_graph_2.setObjectName("select_signal_name_graph_2")
        self.select_signal_name_label_graph_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: italic 10pt \"Georgia\";\n"
"")
        self.gridLayout_2.addWidget(self.select_signal_name_label_graph_2, 0, 0, 1, 1)


        self.signals_name_combo_box_graph_2 = QtWidgets.QComboBox(self.frame_2)
        self.signals_name_combo_box_graph_2.setObjectName("signals_name_combo_box_graph_2")
        self.signals_name_combo_box_graph_2.setStyleSheet("""
            QComboBox {
                background-color: #3c4a68;  /* Background color */
                color: white;  /* Text color */
                border: 1px solid #3c4a68;
                border-radius: 10px;  /* Rounded corners */
                padding: 5px;
                font-size: 14px;
                box-shadow: 2px 2px 5px rgba(0, 0, 0, 0.3);  /* Shadow */
            }
            QComboBox::drop-down {
                border: none;
                border-radius: 10px;  /* Rounded corners for the arrow box */
                background-color: #3c4a68;
                width: 30px;
            }
            QComboBox::down-arrow {
                # image: url(down_arrow.png);  /* You can replace this with a custom arrow icon */
                width: 15px;
                height: 15px;
            }
            QComboBox::down-arrow {
                border: none;
                color: white;  /* Arrow color */
            }
            QComboBox QAbstractItemView {
                border: 1px solid #3c4a68;
                selection-background-color: #5a6478;  /* Selected item background color */
                background-color: #3c4a68;  /* Dropdown background color */
                color: white;
                border-radius: 10px;
            }
        """)


        self.gridLayout_2.addWidget(self.signals_name_combo_box_graph_2, 0, 1, 1, 1)




        self.horizontalLayout_4.addWidget(self.frame_2)
        self.gridLayout_4.addLayout(self.horizontalLayout_4, 5, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(10, -1, 15, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.graph_Label_1 = QtWidgets.QLabel(self.centralwidget)
        self.graph_Label_1.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: italic 11pt \"Georgia\";\n"
"")
        self.graph_Label_1.setTextFormat(QtCore.Qt.PlainText)
        self.graph_Label_1.setObjectName("graph_Label_1")
        self.horizontalLayout.addWidget(self.graph_Label_1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.select_button_graph1 = QtWidgets.QPushButton(self.centralwidget)
        self.select_button_graph1.setMinimumSize(QtCore.QSize(30, 30))
        self.select_button_graph1.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.select_button_graph1.setStyleSheet("font: italic 10pt \"Georgia\";\n"
"font: 12pt \"Georgia\";\n"
"\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(120, 207, 233);\n"
"buttoon-shadow: 2px 2px 5px rgb(0, 0, 0);\n"
"border-radius: 15px;")
        select = QtGui.QIcon()
        select.addPixmap(QtGui.QPixmap("./images/icons8-screenshot-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.select_button_graph1.setText("")
        self.select_button_graph1.setIcon(select)
        self.select_button_graph1.setObjectName("select_button_graph1")
        self.horizontalLayout.addWidget(self.select_button_graph1)
        self.snapshot_button = QtWidgets.QPushButton(self.centralwidget)
        self.snapshot_button.setMinimumSize(QtCore.QSize(30, 30))
        self.snapshot_button.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.snapshot_button.setStyleSheet("font: italic 10pt \"Georgia\";\n"
"font: 12pt \"Georgia\";\n"
"\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(120, 207, 233);\n"
"buttoon-shadow: 2px 2px 5px rgb(0, 0, 0);\n"
"border-radius: 15px;")
        snapshot = QtGui.QIcon()
        snapshot.addPixmap(QtGui.QPixmap("./images/icons8-camera-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.snapshot_button.setText("")
        self.snapshot_button.setIcon(snapshot)
        self.snapshot_button.setObjectName("snapshot_button")
        self.horizontalLayout.addWidget(self.snapshot_button)
        self.play_button_graph_1 = QtWidgets.QPushButton(self.centralwidget)
        self.play_button_graph_1.setCursor(QtGui.QCursor(QtCore.Qt.SplitVCursor))
        self.play_button_graph_1.setMouseTracking(True)
        self.play_button_graph_1.setStyleSheet("font: italic 10pt \"Georgia\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(120, 207, 233);\n"
"buttoon-shadow: 2px 2px 5px rgb(0, 0, 0);\n"
"border-radius: 15px;")
        self.play_button_graph_1.setText("")
        self.play_button_graph_1.setIcon(self.icon)
        self.play_button_graph_1.setObjectName("play_button_graph_1")

        self.play_button_graph_1.setCursor(QtCore.Qt.PointingHandCursor)
        self.play_button_graph_2.setCursor(QtCore.Qt.PointingHandCursor)
        self.reset_button_graph_2.setCursor(QtCore.Qt.PointingHandCursor)
        self.select_button_graph_2.setCursor(QtCore.Qt.PointingHandCursor)
        self.snapshot_button_graph_3.setCursor(QtCore.Qt.PointingHandCursor)
        self.open_button_graph_2.setCursor(QtCore.Qt.PointingHandCursor)
        
        

        self.connect_online_button_graph_2.setCursor(QtCore.Qt.PointingHandCursor)
        # self.zoom_in_button_graph_1.setCursor(QtCore.Qt.PointingHandCursor)
        self.move_to_graph_1_button.setCursor(QtCore.Qt.PointingHandCursor)
        self.play_button_graph_2.setCursor(QtCore.Qt.PointingHandCursor)
        

        self.horizontalLayout.addWidget(self.play_button_graph_1)
        self.select_button_graph_1 = QtWidgets.QPushButton(self.centralwidget)
        self.select_button_graph_1.setCursor(QtGui.QCursor(QtCore.Qt.SplitVCursor))
        self.select_button_graph_1.setMouseTracking(True)
        self.select_button_graph_1.setStyleSheet("font: italic 10pt \"Georgia\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(120, 207, 233);\n"
"buttoon-shadow: 2px 2px 5px rgb(0, 0, 0);\n"
"border-radius: 15px;")
        self.select_button_graph_1.setText("")
        self.select_button_graph_1.setIcon(self.icon1)
        self.select_button_graph_1.setObjectName("select_button_graph_1")
        self.horizontalLayout.addWidget(self.select_button_graph_1)
        self.reset_button_graph_1 = QtWidgets.QPushButton(self.centralwidget)
        self.reset_button_graph_1.setCursor(QtGui.QCursor(QtCore.Qt.SplitVCursor))
        self.reset_button_graph_1.setMouseTracking(True)
        self.reset_button_graph_1.setStyleSheet("font: italic 10pt \"Georgia\";\n"
"color: rgb(34, 40, 62);\n"
"background-color: rgb(120, 207, 233);\n"
"buttoon-shadow: 2px 2px 5px rgb(0, 0, 0);\n"
"border-radius: 15px;")
        self.reset_button_graph_1.setText("ON")
        self.reset_button_graph_1.setIcon(icon6)
        self.reset_button_graph_1.setObjectName("reset_button_graph_1")
        self.horizontalLayout.addWidget(self.reset_button_graph_1)
        self.move_to_graph_2_button = QtWidgets.QPushButton(self.centralwidget)
        self.move_to_graph_2_button.setCursor(QtGui.QCursor(QtCore.Qt.SplitVCursor))
        self.move_to_graph_2_button.setMouseTracking(True)
        self.move_to_graph_2_button.setStyleSheet("font: italic 10pt \"Georgia\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(120, 207, 233);\n"
"buttoon-shadow: 2px 2px 5px rgb(0, 0, 0);\n"
"border-radius: 15px;")
        self.move_to_graph_2_button.setText("")
        # self.move_to_graph_2_button.setIcon(icon3)
        self.move_to_graph_2_button.setIcon(icon5)
        self.move_to_graph_2_button.setObjectName("move_to_graph_2_button")
        self.horizontalLayout.addWidget(self.move_to_graph_2_button)
        self.connect_online_button_graph_1 = QtWidgets.QPushButton(self.centralwidget)
        self.connect_online_button_graph_1.setCursor(QtGui.QCursor(QtCore.Qt.SplitVCursor))
        self.connect_online_button_graph_1.setMouseTracking(True)
        self.connect_online_button_graph_1.setStyleSheet("font: italic 10pt \"Georgia\";\n"
"color: rgb(34, 40, 62);\n"
"background-color: rgb(120, 207, 233);\n"
"buttoon-shadow: 2px 2px 5px rgb(0, 0, 0);\n"
"border-radius: 10px;")
        self.connect_online_button_graph_1.setText("Connect Online")
        self.connect_online_button_graph_1.setObjectName("connect_online_button_graph_1")
        self.horizontalLayout.addWidget(self.connect_online_button_graph_1)
        self.open_button_graph_1 = QtWidgets.QPushButton(self.centralwidget)
        self.open_button_graph_1.setCursor(QtGui.QCursor(QtCore.Qt.SplitVCursor))
        self.open_button_graph_1.setMouseTracking(False)
        self.open_button_graph_1.setStyleSheet("font: italic 10pt \"Georgia\";\n"
"font: 12pt \"Georgia\";\n"
"\n"
"color: rgb(34, 40, 62);\n"
"background-color: rgb(120, 207, 233);\n"
"buttoon-shadow: 2px 2px 5px rgb(0, 0, 0);\n"
"border-radius: 10px;")
        self.open_button_graph_1.setObjectName("open_button_graph_1")
        sizePolicy_button = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy_button.setHorizontalStretch(0)
        sizePolicy_button.setVerticalStretch(0)
        self.open_button_graph_1.setMinimumSize(80, 30)
        self.open_button_graph_1.setSizePolicy(sizePolicy_button)
        self.open_button_graph_2.setMinimumSize(80, 30)
        self.open_button_graph_2.setSizePolicy(sizePolicy_button)
        
        self.connect_online_button_graph_1.setMinimumSize(130, 30)
        self.connect_online_button_graph_2.setMinimumSize(130, 30)
        self.connect_online_button_graph_1.setSizePolicy(sizePolicy_button)
        self.connect_online_button_graph_2.setSizePolicy(sizePolicy_button)

        self.play_button_graph_1.setSizePolicy(sizePolicy_button)
        self.play_button_graph_1.setMinimumSize(30, 30)
        self.play_button_graph_2.setSizePolicy(sizePolicy_button)
        self.play_button_graph_2.setMinimumSize(30, 30)
        
        self.reset_button_graph_1.setSizePolicy(sizePolicy_button)
        self.reset_button_graph_1.setMinimumSize(80, 30)
        self.reset_button_graph_2.setSizePolicy(sizePolicy_button)
        self.reset_button_graph_2.setMinimumSize(80, 30)
       
        self.move_to_graph_2_button.setSizePolicy(sizePolicy_button)
        self.move_to_graph_2_button.setMinimumSize(30, 30)
        self.move_to_graph_1_button.setSizePolicy(sizePolicy_button)
        self.move_to_graph_1_button.setMinimumSize(30, 30)
       
        self.select_button_graph_1.setSizePolicy(sizePolicy_button)
        self.select_button_graph_1.setMinimumSize(30, 30)
        self.select_button_graph_2.setSizePolicy(sizePolicy_button)
        self.select_button_graph_2.setMinimumSize(30, 30)
        self.snapshot_button_graph_3.setSizePolicy(sizePolicy_button)
        self.snapshot_button_graph_3.setMinimumSize(30, 30)

        
        self.link_play_button.setSizePolicy(sizePolicy_button)
        self.link_play_button.setMinimumSize(30, 30)
        self.link_rewind_button.setSizePolicy(sizePolicy_button)
        self.link_rewind_button.setMinimumSize(30, 30)

        self.connect_online_button_graph_1.setCursor(QtCore.Qt.PointingHandCursor)
        self.reset_button_graph_1.setCursor(QtCore.Qt.PointingHandCursor)
        self.open_button_graph_1.setCursor(QtCore.Qt.PointingHandCursor)
        self.select_button_graph_1.setCursor(QtCore.Qt.PointingHandCursor)
        self.move_to_graph_2_button.setCursor(QtCore.Qt.PointingHandCursor)

        self.signal_color_button_graph_1.setCursor(QtCore.Qt.PointingHandCursor)
        self.signal_color_button_graph_2.setCursor(QtCore.Qt.PointingHandCursor)
        self.signal_color_button_graph_1.setMinimumSize(150, 30)
        self.signal_color_button_graph_2.setMinimumSize(150, 30)
       
        self.horizontalLayout.addWidget(self.open_button_graph_1)
        self.gridLayout_4.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        # spacerItem6 = QtWidgets.QSpacerItem(5, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        # self.verticalLayout.addItem(spacerItem6)
        spacerItem6 = QtWidgets.QSpacerItem(27, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.nonrectangle_graph_button = QtWidgets.QPushButton(self.centralwidget)
        self.nonrectangle_graph_button.setMinimumSize(QtCore.QSize(170, 30))
        self.nonrectangle_graph_button.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.nonrectangle_graph_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.nonrectangle_graph_button.setStyleSheet("font: italic 10pt \"Georgia\";\n"
"font: 12pt \"Georgia\";\n"
"\n"
"color: rgb(34, 40, 62);\n"
"background-color: rgb(120, 207, 233);\n"
"buttoon-shadow: 2px 2px 5px rgb(0, 0, 0);\n"
"border-radius: 10px;")
        self.nonrectangle_graph_button.setObjectName("nonrectangle_graph_button")
        self.horizontalLayout.addWidget(self.nonrectangle_graph_button)
        self.export_button = QtWidgets.QPushButton(self.centralwidget)
        self.export_button.setMinimumSize(QtCore.QSize(140, 30))
        self.export_button.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.export_button.setStyleSheet("font: italic 10pt \"Georgia\";\n"
"font: 12pt \"Georgia\";\n"
"\n"
"color: rgb(34, 40, 62);\n"
"background-color: rgb(120, 207, 233);\n"
"buttoon-shadow: 2px 2px 5px rgb(0, 0, 0);\n"
"border-radius: 10px;")
        self.export_button.setObjectName("export_button")
        self.horizontalLayout.addWidget(self.export_button)
        self.signalViewerLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.signalViewerLabel.sizePolicy().hasHeightForWidth())
        self.signalViewerLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft PhagsPa")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.signalViewerLabel.setFont(font)
        self.signalViewerLabel.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 20pt \"Microsoft PhagsPa\";")
        self.signalViewerLabel.setTextFormat(QtCore.Qt.PlainText)
        self.signalViewerLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.signalViewerLabel.setObjectName("signalViewerLabel")
        self.verticalLayout.addWidget(self.signalViewerLabel)
        self.gridLayout_4.addLayout(self.verticalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.retranslateUi(MainWindow)



        # Layout for speed control of graph 1
        #self.speedControlLayoutGraph1 = QHBoxLayout()
        # self.speedControlLayoutGraph1.addWidget(self.speedLabelGraph1)
        # self.speedControlLayoutGraph1.addWidget(self.speedSliderGraph1)

        # Layout for speed control of graph 2
        # self.speedControlLayoutGraph2 = QHBoxLayout()
        # self.speedLabelGraph2 = QLabel("Speed Graph 2:")
        # self.speedSliderGraph2 = QSlider(QtCore.Qt.Horizontal)
        # self.speedSliderGraph2.setMinimum(50)  # Minimum speed interval (in ms)
        # self.speedSliderGraph2.setMaximum(1000)  # Maximum speed interval (in ms)
        # self.speedSliderGraph2.setValue(500)  # Default speed interval (in ms)

        # self.speedControlLayoutGraph2.addWidget(self.speedLabelGraph2)
        # self.speedControlLayoutGraph2.addWidget(self.speedSliderGraph2)

        # # Adding speed control layouts to the main layout
        # self.mainLayout = QVBoxLayout(self.centralwidget)  # Assuming you have a central widget
        # self.mainLayout.addLayout(self.speedControlLayoutGraph1)
        # self.mainLayout.addLayout(self.speedControlLayoutGraph2)

        # # Additional layouts and widgets...
        # # self.mainLayout.addWidget(self.otherWidget)
        
        # MainWindow.setCentralWidget(self.centralwidget)




        #self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        #self.open_button_graph_1.clicked.connect(self.open_file)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.signal_color_button_graph_1.setToolTip("")
        self.signal_color_button_graph_1.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">)pen</span></p></body></html>"))
        self.signal_color_button_graph_1.setText(_translate("MainWindow", "Signal\'s Color"))
        self.visible_checkBox_graph_1.setText(_translate("MainWindow", "Visible"))
        self.speed_label_graph_1.setText(_translate("MainWindow", "Cine Speed"))
        self.select_signal_name_label_graph_1.setText(_translate("MainWindow", "Select Signal"))
        self.select_signal_name_label_graph_2.setText(_translate("MainWindow", "Select Signal"))
        self.speed_label_graph_2.setText(_translate("MainWindow", "Cine Speed"))
        self.signal_name_label_graph_1.setText(_translate("MainWindow", "Signal\'s Name"))
        # self.graph_Label_2.setText(_translate("MainWindow", "Graph 2"))
        self.link_button.setText(_translate("MainWindow", "Link"))
        self.link_play_button.setToolTip("")
        self.link_play_button.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">)pen</span></p></body></html>"))
        self.link_rewind_button.setToolTip("")
        self.link_rewind_button.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">)pen</span></p></body></html>"))
        self.play_button_graph_2.setToolTip("")
        self.play_button_graph_2.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">)pen</span></p></body></html>"))
        self.select_button_graph_2.setToolTip("")
        self.select_button_graph_2.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">)pen</span></p></body></html>"))
        self.reset_button_graph_2.setToolTip("")
        self.reset_button_graph_2.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">)pen</span></p></body></html>"))
        self.move_to_graph_1_button.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
      
       
        self.move_to_graph_1_button.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">)pen</span></p></body></html>"))
        self.connect_online_button_graph_2.setToolTip("")
        self.connect_online_button_graph_2.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">)pen</span></p></body></html>"))
        self.open_button_graph_2.setToolTip("")
        self.open_button_graph_2.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">)pen</span></p></body></html>"))
        self.open_button_graph_2.setText(_translate("MainWindow", "Open"))
        self.signal_name_label_graph_3.setText(_translate("MainWindow", "Signal\'s Name"))
        # self.visible_checkBox_graph_3.setText(_translate("MainWindow", "Visible"))
        self.graph_Label_3.setText(_translate("MainWindow", "Graph 3"))
        self.snapshot_button_graph_3.setToolTip("")
        self.snapshot_button_graph_3.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">)pen</span></p></body></html>"))
        self.signal_name_label_graph_3.setText(_translate("MainWindow", "interpolation"))
        self.pushButton.setText(_translate("MainWindow", "Glue"))
        self.signal_name_label_graph_2.setText(_translate("MainWindow", "Signal\'s Name"))
        self.visible_checkBox_graph_2.setText(_translate("MainWindow", "Visible"))
        self.signal_color_button_graph_2.setToolTip("")
        self.signal_color_button_graph_2.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">)pen</span></p></body></html>"))
        self.signal_color_button_graph_2.setText(_translate("MainWindow", "Signal\'s Color"))
        self.graph_Label_1.setText(_translate("MainWindow", "Graph 1"))
        self.play_button_graph_1.setToolTip("")
        self.play_button_graph_1.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">)pen</span></p></body></html>"))
        self.select_button_graph_1.setToolTip("")
        self.select_button_graph_1.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">)pen</span></p></body></html>"))
        self.reset_button_graph_1.setToolTip("")
        self.reset_button_graph_1.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">)pen</span></p></body></html>"))
        self.move_to_graph_2_button.setToolTip("")
        self.move_to_graph_2_button.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">)pen</span></p></body></html>"))
        self.connect_online_button_graph_1.setToolTip("")
        self.connect_online_button_graph_1.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">)pen</span></p></body></html>"))
        self.open_button_graph_1.setToolTip("")
        self.open_button_graph_1.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">)pen</span></p></body></html>"))
        self.open_button_graph_1.setText(_translate("MainWindow", "Open"))
        self.nonrectangle_graph_button.setText(_translate("MainWindow", "Non-Rectangle "))
        self.export_button.setText(_translate("MainWindow", "Export Report"))
        self.signalViewerLabel.setText(_translate("MainWindow", "Real-Time Signal Viewer"))